stages:
  - build
  - test
  - push
  - deploy

variables:
  DOCKERFILE_PATH: ./docker
  FRONT_END_SRC_PATH: .

  PROJECT_NAME: erp-webapp
  AWS_REGISTRY_URL: 009795078640.dkr.ecr.ap-southeast-1.amazonaws.com

fe.build:
  stage: build
  before_script:
    - aws ecr get-login-password --region ap-southeast-1 | docker login  --username AWS  --password-stdin 009795078640.dkr.ecr.ap-southeast-1.amazonaws.com
    - >
      if git diff HEAD~ --name-only | grep -i 'package.json\|package-lock.json\|builder.Dockerfile\|internals'; then
        docker build -f $DOCKERFILE_PATH/builder.Dockerfile -t $AWS_REGISTRY_URL/$PROJECT_NAME:builder $FRONT_END_SRC_PATH
        docker push $AWS_REGISTRY_URL/$PROJECT_NAME:builder
      fi;
  script:
    - docker pull $AWS_REGISTRY_URL/$PROJECT_NAME:builder || true
    - docker build --cache-from $AWS_REGISTRY_URL/$PROJECT_NAME:$CI_COMMIT_REF_SLUG -f $DOCKERFILE_PATH/staging.Dockerfile -t $AWS_REGISTRY_URL/$PROJECT_NAME:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHA $FRONT_END_SRC_PATH
    - docker push $AWS_REGISTRY_URL/$PROJECT_NAME:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHA
  only:
    - develop
    - release
    - tags

fe.push.staging:
  stage: push
  variables:
    GIT_STRATEGY: none
  dependencies:
    - fe.build
  script:
    - docker pull $AWS_REGISTRY_URL/$PROJECT_NAME:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHA
    - docker tag $AWS_REGISTRY_URL/$PROJECT_NAME:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHA $AWS_REGISTRY_URL/$PROJECT_NAME:$CI_COMMIT_REF_SLUG
    - docker push $AWS_REGISTRY_URL/$PROJECT_NAME:$CI_COMMIT_REF_SLUG
    - docker rmi $AWS_REGISTRY_URL/$PROJECT_NAME:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHA
  only:
    - develop
    - release

fe.deploy.staging:
  stage: deploy
  variables:
    GIT_STRATEGY: none
  dependencies:
    - fe.push.staging
  script:
    - docker pull $AWS_REGISTRY_URL/$PROJECT_NAME:$CI_COMMIT_REF_SLUG
    - cd deployment && docker-compose down && docker-compose -f docker-compose.staging.yml up -d
  only:
    - develop

fe.push.tag:
  stage: push
  variables:
    GIT_STRATEGY: none
  dependencies:
    - fe.build
  script:
    - docker pull $AWS_REGISTRY_URL/$PROJECT_NAME:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHA
    - docker tag $AWS_REGISTRY_URL/$PROJECT_NAME:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHA $AWS_REGISTRY_URL/$PROJECT_NAME:$CI_COMMIT_TAG
    - docker push $AWS_REGISTRY_URL/$PROJECT_NAME:$CI_COMMIT_TAG
    - docker rmi $AWS_REGISTRY_URL/$PROJECT_NAME:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHA
  only:
    - tags
