export const WINDOW_WIDTH = window.innerWidth;

export const styles = (theme) => ({
  root: {
    width: '100%',
    border: 'none',
    paddingLeft: theme.spacing.unit * 2,
    paddingRight: theme.spacing.unit * 2,
    paddingBottom: theme.spacing.unit * 2,
    paddingTop: theme.spacing.unit * 2,
    marginBottom: theme.spacing.unit * 4,
  },
  toolbar: {
    width: '100%',
    border: 'none',
    paddingBottom: theme.spacing.unit * 2,
    paddingTop: theme.spacing.unit * 2,
  },
  category: {
    background: '#3b4756',
    color: 'white',
  },
  heading: {
    fontSize: theme.typography.pxToRem(18),
    flexBasis: '100%',
    flexShrink: 0,
    color: 'white',
  },
  secondaryHeading: {
    fontSize: theme.typography.pxToRem(15),
    color: theme.palette.text.secondary,
  },
  center: {
    textAlign: 'center',
  },
  right: {
    textAlign: 'right',
  },
  button: {
    margin: theme.spacing.unit,
    // height: 36,
    // width: 36,
  },
  hidden: {
    display: 'none',
  },
  description: {
    fontSize: '12px',
  },
  boolType: {
    padding: 0,
  },
  settingTab: {
    padding: 10,
  },
  wrapper: {
    width: '100%',
    marginBottom: 10,
  },
  input: { width: '100%' },
  panel: { boxShadow: 'none' },
  rightIcon: {
    marginRight: theme.spacing.unit,
  },
  iconSmall: {
    fontSize: 20,
  },
  buttonLogo: {
    border: '1px dashed gray',
    width: 180,
    height: 60,
    textAlign: 'center',
    backgroundSize: 'cover',
    backgroundRepeat: 'no-repeat',
    backgroundPosition: 'center',
  },
  title: {
    flex: '0 0 auto',
  },
  actions: {
    color: theme.palette.text.secondary,
    width: WINDOW_WIDTH >= 768 ? WINDOW_WIDTH / 6 : WINDOW_WIDTH / 2,
    textAlign: 'right',
  },
  spacer: {
    flex: '1 1 90%',
  },
  table: {
    minWidth: 'auto',
  },
  tableWrapper: {
    height: 'calc(100vh - 305px)',
    // borderBottom: `1px solid ${theme.palette.primary.border}`,
  },
  tableHeader: {
    color: theme.palette.primary.color,
    textAlign: 'left',
    flexDirection: 'row',
    fontWeight: 'bold',
    // border: '1px solid red',
    backgroundColor: '#ffffff',
    position: 'sticky',
    top: 0,
    zIndex: 1,
    borderBottom: `1px solid ${theme.palette.primary.border}`,
    padding: '5px',
  },
  tableSubHeader: {
    color: theme.palette.primary.color,
    flexDirection: 'row',
    fontWeight: 'bold',
    // border: '1px solid red',
    backgroundColor: '#ffffff',
    position: 'sticky',
    top: 0,
    zIndex: 1,
    padding: '10px',
    borderBottom: `1px solid ${theme.palette.primary.border}`,
    // borderLeft: `2px solid ${theme.palette.primary.border}`,
    // borderRight: `2px solid ${theme.palette.primary.border}`,
    // padding: '5px'
  },
  tableHeaderCenter: {
    textAlign: 'center',
  },
  cellTableCheckBoxHeader: {
    color: theme.palette.primary.color,
    minHeight: '40px',
    height: '40px',
    width: '50px',
    padding: '1px',
    textAlign: 'left',
    flexDirection: 'row',
    fontWeight: 'bold',
    // border: '1px solid red',
    backgroundColor: '#ffffff',
    position: 'sticky',
    top: 0,
    zIndex: 1,
    borderBottom: `2px solid ${theme.palette.primary.border}`,
  },
  cellTableCheckBox: {
    color: theme.palette.primary.color,
    minHeight: '40px',
    height: '40px',
    width: '50px',
    padding: '1px',
    // border: '1px solid red',
  },
  cellTableBody: {
    color: theme.palette.primary.color,
    minHeight: '40px',
    height: '40px',
    minWidth: 'auto',
    // border: 'none',
    // whiteSpace: 'nowrap',
    padding: '5px',
    fontWeight: 'normal',
  },
  cellTableBodyCenter: {
    color: theme.palette.primary.color,
    // border: 'none',
    textAlign: 'center',
    whiteSpace: 'nowrap',
    minHeight: '40px',
    height: '40px',
    // border: '1px solid black',
  },
  iconActionInCell: {
    padding: 3,
    minWidth: '1.3em',
  },
  buttonContainer: {
    textAlign: 'right',
    marginTop: theme.spacing.unit * 2,
    marginBottom: theme.spacing.unit * 2,
  },
  buttonToolbar: {
    marginLeft: 15,
  },
  image: {
    // width: '80%',
    width: '150px',
    height: '200px',
    margin: theme.spacing.unit,
    padding: theme.spacing.unit,
    border: 'solid 1px #ccc',
    // backgroundColor: '#ccc',
  },
  uploadContainer: {
    position: 'relative',
  },
  uploadOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: '100%',
    height: '100%',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    color: '#fff',
    cursor: 'pointer',
  },
  uploadImg: {
    color: 'rgba(0, 0, 0, 0.54)',
    padding: 0,
    fontSize: '12px',
    fontFamily: "'Roboto', 'Helvetica', 'Arial', sans-serif",
    lineHeight: 1,
  },
  addImageBtn: {
    position: 'absolute',
    bottom: 10,
    right: 10,
    background: 'white',
    width: 30,
    height: 30,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
});
