/*
 * CHANGE_PASSWORDConstants
 * Each action has a corresponding type, which the reducer knows and picks up on.
 * To avoid weird typos between the reducer and the actions, we save them as
 * constants here. We prefix them with 'yourproject/YourComponent' so we avoid
 * reducers accidentally picking up actions they shouldn't.
 *
 * Follow this format:
 * export const YOUR_ACTION_CONSTANT = 'yourproject/YourContainer/YOUR_ACTION_CONSTANT';
 */
export const GET_CHANGE_PASSWORD_DATA_SUCCESS =
  'demasterpro/CHANGE_PASSWORD/GET_CHANGE_PASSWORD_DATA_SUCCESS';
export const UPDATE_CHANGE_PASSWORD =
  'demasterpro/CHANGE_PASSWORD/UPDATE_CHANGE_PASSWORD';
export const ADD_CHANGE_PASSWORD =
  'demasterpro/CHANGE_PASSWORD/ADD_CHANGE_PASSWORD';
export const INIT_INDEX_CHANGE_PASSWORD =
  'demasterpro/CHANGE_PASSWORD/INIT_INDEX_CHANGE_PASSWORD';
export const INIT_INDEX_CHANGE_PASSWORD_SUCCESS =
  'demasterpro/CHANGE_PASSWORD/INIT_INDEX_CHANGE_PASSWORD_SUCCESS';
export const CHANGE_TEXT_FIELD =
  'demasterpro/CHANGE_PASSWORD/CHANGE_TEXT_FIELD';
export const DELETE_CHANGE_PASSWORD_ROW =
  'demasterpro/CHANGE_PASSWORD/DELETE_CHANGE_PASSWORD_ROW';
export const VALIDATE_CHANGE_PASSWORD_ERROR =
  'demasterpro/CHANGE_PASSWORD/VALIDATE_CHANGE_PASSWORD_ERROR';
export const CREATE_CHANGE_PASSWORD_SUCCESS =
  'demasterpro/CHANGE_PASSWORD/CREATE_CHANGE_PASSWORD_SUCCESS';
export const UPDATE_CHANGE_PASSWORD_SUCCESS =
  'demasterpro/CHANGE_PASSWORD/UPDATE_CHANGE_PASSWORD_SUCCESS';
export const DELETE_CHANGE_PASSWORD_SUCCESS =
  'demasterpro/CHANGE_PASSWORD/DELETE_CHANGE_PASSWORD_SUCCESS';
export const SET_META_CHANGE_PASSWORD =
  'demasterpro/CHANGE_PASSWORD/SET_META_CHANGE_PASSWORD';
export const DELETE_MULTIES_CHANGE_PASSWORD =
  'demasterpro/CHANGE_PASSWORD/DELETE_MULTIES_CHANGE_PASSWORD';
export const DELETE_MULTIES_CHANGE_PASSWORD_SUCCESS =
  'demasterpro/CHANGE_PASSWORD/DELETE_MULTIES_CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PAGE_NUMBER_CHANGE_PASSWORD =
  'demasterpro/CHANGE_PASSWORD/CHANGE_PAGE_NUMBER_CHANGE_PASSWORD';
export const CHANGE_PAGE_SIZE_CHANGE_PASSWORD =
  'demasterpro/CHANGE_PASSWORD/CHANGE_PAGE_SIZE_CHANGE_PASSWORD';
export const FETCH_CHANGE_PASSWORD_DATA =
  'demasterpro/CHANGE_PASSWORD/FETCH_CHANGE_PASSWORD_DATA';
export const FETCH_CHANGE_PASSWORD_INIT =
  'demasterpro/CHANGE_PASSWORD/FETCH_CHANGE_PASSWORD_INIT';
export const GET_SORT_CHANGE_PASSWORD_LIST =
  'demasterpro/CHANGE_PASSWORD/GET_SORT_CHANGE_PASSWORD_LIST';
export const GET_SORT_DIRECTION_CHANGE_PASSWORD_LIST =
  'demasterpro/CHANGE_PASSWORD/GET_SORT_DIRECTION_CHANGE_PASSWORD_LIST';
export const VALIDATE_CHANGE_PASSWORD =
  'demasterpro/CHANGE_PASSWORD/VALIDATE_CHANGE_PASSWORD';
export const SET_STATUS_LIST_CHANGE_PASSWORD =
  'demasterpro/CHANGE_PASSWORD/SET_STATUS_LIST_CHANGE_PASSWORD';
export const SET_GENDER_LIST_CHANGE_PASSWORD =
  'demasterpro/CHANGE_PASSWORD/SET_GENDER_LIST_CHANGE_PASSWORD';
export const SET_DEPARTMENTS_LIST_CHANGE_PASSWORD =
  'demasterpro/CHANGE_PASSWORD/SET_DEPARTMENTS_LIST_CHANGE_PASSWORD';
export const SET_WORKTYPES_LIST_CHANGE_PASSWORD =
  'demasterpro/CHANGE_PASSWORD/SET_WORKTYPES_LIST_CHANGE_PASSWORD';
export const UPDATE_AVATAR = 'demasterpro/CHANGE_PASSWORD/UPDATE_AVATAR';
export const SET_STORE_LIST_WAITING =
  'demasterpro/CHANGE_PASSWORD/SET_STORE_LIST_WAITING';
export const SET_USER_CHANGE_PASSWORD =
  'demasterpro/CHANGE_PASSWORD/SET_USER_CHANGE_PASSWORD';
export const REQUEST_JOIN_GROUP =
  'demasterpro/CHANGE_PASSWORD/REQUEST_JOIN_GROUP';
export const GET_FRIEND_DATA = 'demasterpro/CHANGE_PASSWORD/GET_FRIEND_DATA';
export const GET_FRIEND_DATA_SUCCESS =
  'demasterpro/CHANGE_PASSWORD/GET_FRIEND_DATA_SUCCESS';
export const DELETE_MULTIES_FRIEND =
  'demasterpro/CHANGE_PASSWORD/DELETE_MULTIES_FRIEND';
export const DELETE_MULTIES_FRIEND_SUCCESS =
  'demasterpro/CHANGE_PASSWORD/DELETE_MULTIES_FRIEND_SUCCESS';
export const USER_OUT_GROUP = 'demasterpro/CHANGE_PASSWORD/USER_OUT_GROUP';
export const USER_OUT_GROUP_SUCCESS =
  'demasterpro/CHANGE_PASSWORD/USER_OUT_GROUP_SUCCESS';
export const REQUEST_ADD_FRIEND =
  'demasterpro/CHANGE_PASSWORD/REQUEST_ADD_FRIEND';
export const CHANGE_PASSWORD = 'demasterpro/CHANGE_PASSWORD/CHANGE_PASSWORD';
export const CHANGE_PASSWORD_SUCCESS =
  'demasterpro/CHANGE_PASSWORD/CHANGE_PASSWORD_SUCCESS';
